// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"

	"github.com/PakaiWA/PakaiWA/ent/permission"
	"github.com/PakaiWA/PakaiWA/ent/schema"
	"github.com/PakaiWA/PakaiWA/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescPath is the schema descriptor for path field.
	permissionDescPath := permissionFields[1].Descriptor()
	// permission.PathValidator is a validator for the "path" field. It is called by the builders before save.
	permission.PathValidator = permissionDescPath.Validators[0].(func(string) error)
	// permissionDescMethod is the schema descriptor for method field.
	permissionDescMethod := permissionFields[2].Descriptor()
	// permission.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	permission.MethodValidator = permissionDescMethod.Validators[0].(func(string) error)
	// permissionDescAccess is the schema descriptor for access field.
	permissionDescAccess := permissionFields[3].Descriptor()
	// permission.AccessValidator is a validator for the "access" field. It is called by the builders before save.
	permission.AccessValidator = permissionDescAccess.Validators[0].(func(string) error)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[4].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionFields[0].Descriptor()
	// permission.DefaultID holds the default value on creation for the id field.
	permission.DefaultID = permissionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescLogoutAt is the schema descriptor for logout_at field.
	userDescLogoutAt := userFields[3].Descriptor()
	// user.DefaultLogoutAt holds the default value on creation for the logout_at field.
	user.DefaultLogoutAt = userDescLogoutAt.Default.(func() time.Time)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
